version: "3"
services:
  nonginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./log:/log"
      - "./www:/www"
      - "./conf:/etc/nginx/conf.d"
    networks:
      - noNet

networks:
  noNet:
    driver: bridge
    